apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-replica-2
parameters:
  dataLocality: disabled
  fromBackup: ""
  fsType: xfs
  nfsOptions: "vers=4.2,noresvport,softerr,timeo=600,retrans=5"
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true